//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/Input Map.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMap : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Map"",
    ""maps"": [
        {
            ""name"": ""Drawing"",
            ""id"": ""cfb94a4c-567e-42d5-8138-06dedce60017"",
            ""actions"": [
                {
                    ""name"": ""Press"",
                    ""type"": ""Button"",
                    ""id"": ""cd84ad91-011f-4ac5-8628-a1d0fb9b9d06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""35d20ccf-7a1c-4872-8489-b54c8f46a8f7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3e6b780b-13ad-4c97-9680-eca9bef73978"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a2178bf-b37f-4f1b-9d01-82d7ee0c5a58"",
                    ""path"": ""<Pen>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6116ba70-f4e9-4943-8007-014706614baa"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8c2ce9e-0271-43b5-bdbb-e96eaafa6da9"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Drawing
        m_Drawing = asset.FindActionMap("Drawing", throwIfNotFound: true);
        m_Drawing_Press = m_Drawing.FindAction("Press", throwIfNotFound: true);
        m_Drawing_Position = m_Drawing.FindAction("Position", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Drawing
    private readonly InputActionMap m_Drawing;
    private IDrawingActions m_DrawingActionsCallbackInterface;
    private readonly InputAction m_Drawing_Press;
    private readonly InputAction m_Drawing_Position;
    public struct DrawingActions
    {
        private @InputMap m_Wrapper;
        public DrawingActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Press => m_Wrapper.m_Drawing_Press;
        public InputAction @Position => m_Wrapper.m_Drawing_Position;
        public InputActionMap Get() { return m_Wrapper.m_Drawing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DrawingActions set) { return set.Get(); }
        public void SetCallbacks(IDrawingActions instance)
        {
            if (m_Wrapper.m_DrawingActionsCallbackInterface != null)
            {
                @Press.started -= m_Wrapper.m_DrawingActionsCallbackInterface.OnPress;
                @Press.performed -= m_Wrapper.m_DrawingActionsCallbackInterface.OnPress;
                @Press.canceled -= m_Wrapper.m_DrawingActionsCallbackInterface.OnPress;
                @Position.started -= m_Wrapper.m_DrawingActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_DrawingActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_DrawingActionsCallbackInterface.OnPosition;
            }
            m_Wrapper.m_DrawingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Press.started += instance.OnPress;
                @Press.performed += instance.OnPress;
                @Press.canceled += instance.OnPress;
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
            }
        }
    }
    public DrawingActions @Drawing => new DrawingActions(this);
    public interface IDrawingActions
    {
        void OnPress(InputAction.CallbackContext context);
        void OnPosition(InputAction.CallbackContext context);
    }
}
